#!/usr/bin/env bash

echo -e "Default profile: should apply config \c"
./cli config-profile set FOO=DEFAULT_BAR
./test/assert $(./cli checkconf | grep "FOO") "FOO=DEFAULT_BAR"

echo -e "Default profile: should change config \c"
./cli config-profile set FOO=DEFAULT_BAR_CHANGED
./test/assert $(./cli checkconf | grep "FOO") "FOO=DEFAULT_BAR_CHANGED"

echo -e "<ANY> Profile: should apply config \c"
./cli config-profile -n test set FOO=BAR
./test/assert $(./cli --profile test checkconf | grep "FOO") "FOO=BAR"
echo -e "<ANY> Profile: should not affect on Default profile config \c"
./test/assert $(./cli checkconf | grep "FOO") "FOO=DEFAULT_BAR_CHANGED"

echo -e "<ANY> profile: should change config \c"
./cli config-profile -n test set FOO=BAR_CHANGED
./test/assert $(./cli --profile test checkconf | grep "FOO") "FOO=BAR_CHANGED"
