#!/usr/bin/env bash

echo -e "CLI config-profile:"
echo -e "Default profile"
./cli config-profile set FOO=DEFAULT_BAR
./test/assert "should apply config" \
$(./cli checkconf | grep "FOO") "FOO=DEFAULT_BAR"

./cli config-profile set FOO=DEFAULT_BAR_CHANGED
./test/assert "should change config" \
$(./cli checkconf | grep "FOO") "FOO=DEFAULT_BAR_CHANGED"

echo -e "<ANY> Profile:"
./cli config-profile -n test set FOO=BAR
./test/assert "should apply config" \
$(./cli --profile test checkconf | grep "FOO") "FOO=BAR"

./test/assert "should not affect on Default profile config" \
$(./cli checkconf | grep "FOO") "FOO=DEFAULT_BAR_CHANGED"

./cli config-profile -n test set FOO=BAR_CHANGED
./test/assert "should change config" \
$(./cli --profile test checkconf | grep "FOO") "FOO=BAR_CHANGED"
