#!/usr/bin/env bash

echo -e "Default profile: should start services with default env variables \c"
./test/assert $(docker ps --format "{{.Names}} {{.Ports}}" | grep "cli_default_adminer 0.0.0.0:4000->8080/tcp" | wc -l) 1
