#!/bin/bash

set -e
export ENVROOT=$(cd $(dirname $0) && pwd)

usage() {
  cli_name=${0##*/}
  echo "
$cli_name
Your env CLI
Version: $(cat $ENVROOT/VERSION)
Usage: $cli_name [command]
Commands:
    docker    Up and running dockers container
    *         Help
"
  exit 1
}

# Handle the environment settings
# Default environment will be dev
# Use options -e | --env to set environment
# Only accept dev | test
set -e
export ENV='dev'

env() {
  ENV=$1

  if [[ -z "$ENV" ]]; then
    ENV="dev"
  fi

  if [[ "$ENV" != "dev" ]] && [[ "$ENV" != "test" ]]; then
    echo "-e only accept values ['dev', 'test']"
    exit 1
  fi

  set -e
  export ENV="$ENV"
}

log_info() {
  echo "CLI running with ENV: $ENV"
}

while [ "$1" != "" ]; do
    case $1 in
        -e | --env )            shift
                                env $1
                                ;;
        docker )                shift
                                log_info
                                "$ENVROOT/bin/docker-run" $@
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
